services:
  shop:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_REST_API_ENDPOINT=${NEXT_PUBLIC_REST_API_ENDPOINT:-http://localhost/}
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-http://localhost:3003}
        - NEXT_PUBLIC_DEFAULT_LANGUAGE=${NEXT_PUBLIC_DEFAULT_LANGUAGE:-en}
        - NEXT_PUBLIC_ENABLE_MULTI_LANG=${NEXT_PUBLIC_ENABLE_MULTI_LANG:-false}
        - NEXT_PUBLIC_AVAILABLE_LANGUAGES=${NEXT_PUBLIC_AVAILABLE_LANGUAGES:-en}
        - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-}
        - NEXT_PUBLIC_GOOGLE_MAP_API_KEY=${NEXT_PUBLIC_GOOGLE_MAP_API_KEY:-}
        - NEXT_PUBLIC_VERSION=${NEXT_PUBLIC_VERSION:-6.8.0}
        - REVALIDATE_DURATION=${REVALIDATE_DURATION:-120}
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3003}
      - SECRET=${SECRET:-}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID:-}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET:-}
    restart: unless-stopped
